/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.unicesumar.view;

import br.edu.unicesumar.code.entity.Cadastro;
import br.edu.unicesumar.code.entity.DAO.CadastroDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Matheus
 */
public class TelaCadastroo extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroo
     */
    public TelaCadastroo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        camposalvarcadastro1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        camposalvarcadastro2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        label5 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        campoLogin1 = new java.awt.TextField();
        campoLogin2 = new java.awt.TextField();
        campoLogin3 = new java.awt.TextField();
        campoLogin4 = new java.awt.TextField();
        camposalvarcadastro = new javax.swing.JButton();

        camposalvarcadastro1.setBackground(new java.awt.Color(204, 255, 255));
        camposalvarcadastro1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        camposalvarcadastro1.setText("Salvar");
        camposalvarcadastro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camposalvarcadastro1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        camposalvarcadastro2.setBackground(new java.awt.Color(204, 255, 255));
        camposalvarcadastro2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        camposalvarcadastro2.setText("Salvar");
        camposalvarcadastro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camposalvarcadastro2ActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastrar Novo Usuário");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        label5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        label5.setText("Nome:");

        label2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        label2.setText("Login:");

        label3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        label3.setText("Senha:");

        label4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        label4.setText("Email:");

        campoLogin1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        campoLogin1.setForeground(new java.awt.Color(0, 0, 0));
        campoLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLogin1ActionPerformed(evt);
            }
        });

        campoLogin2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        campoLogin2.setForeground(new java.awt.Color(0, 0, 0));
        campoLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLogin2ActionPerformed(evt);
            }
        });

        campoLogin3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        campoLogin3.setForeground(new java.awt.Color(0, 0, 0));
        campoLogin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLogin3ActionPerformed(evt);
            }
        });

        campoLogin4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        campoLogin4.setForeground(new java.awt.Color(0, 0, 0));
        campoLogin4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLogin4ActionPerformed(evt);
            }
        });

        camposalvarcadastro.setBackground(new java.awt.Color(204, 255, 255));
        camposalvarcadastro.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        camposalvarcadastro.setText("Salvar");
        camposalvarcadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camposalvarcadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoLogin4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoLogin3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(camposalvarcadastro))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(55, 55, 55)
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(campoLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoLogin2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoLogin4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoLogin3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(camposalvarcadastro)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLogin1ActionPerformed

    private void campoLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLogin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLogin2ActionPerformed

    private void campoLogin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLogin3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLogin3ActionPerformed

    private void campoLogin4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLogin4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLogin4ActionPerformed

    private void camposalvarcadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camposalvarcadastroActionPerformed

        Cadastro cd = new Cadastro();
        cd.setNome(campoLogin1.getText());
        cd.setLogin(campoLogin2.getText());
        cd.setSenha(campoLogin4.getText());
        cd.setEmail(campoLogin3.getText());
        CadastroDAO ce = new CadastroDAO();
        ce.inserir(cd);
        limparTela();
        JOptionPane.showMessageDialog(rootPane, "Produto cadastrado com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_camposalvarcadastroActionPerformed

    private void limparTela(){
        campoLogin1.setText("");
        campoLogin2.setText("");
        campoLogin3.setText("");
        campoLogin4.setText("");
}
    private void camposalvarcadastro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camposalvarcadastro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_camposalvarcadastro1ActionPerformed

    private void camposalvarcadastro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camposalvarcadastro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_camposalvarcadastro2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField campoLogin1;
    private java.awt.TextField campoLogin2;
    private java.awt.TextField campoLogin3;
    private java.awt.TextField campoLogin4;
    private javax.swing.JButton camposalvarcadastro;
    private javax.swing.JButton camposalvarcadastro1;
    private javax.swing.JButton camposalvarcadastro2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    // End of variables declaration//GEN-END:variables
}
